### ISSUE TITLE
Resultado en el terminal, pero no se muestra el dock

### ISSUE THREAD

**Issue by elav** [audoban/Candil-Dock#2]
`systeminside:~ $ candil 
[debug 23:59:26.434434] - package is valid true
[debug 23:59:26.434434] - Candil::DockCorona the package QJsonObject({"KPlugin":{"Authors":[{"Email":"audoban@openmailbox.org","Name":"audoban(smith ar)"}],"Id":"audoban.shell.candildock","License":"GPLv3+","Name":"Candil Dock Shell","Name[en]":"Candil Dock shell","Name[es]":"Shell de Candil Dock","ServiceTypes":["Plasma/Shell"],"Version":"1.0","Website":"https://github.com/audoban/CandilDock"},"Keywords":"shell","X-KDE-ParentApp":"candil"}) is valid!
[warning 23:59:26.510510] - "file:///usr/share/plasma/shells/audoban.shell.candildock/contents/views/Dock.qml" 
 "Error loading QML file.\n21: module \"QtQuick.Controls\" version 2.0 is not installed\n"
?libKF5Declarative.so.5?
[debug 23:59:26.511511] - containment changed
[debug 23:59:26.511511] - visibility mode Normal
[debug 23:59:26.511511] - candil wid: 52428813
[debug 23:59:26.511511] - showing temporarily
[warning 23:59:26.511511] - Could not set containment property on rootObject
?libKF5PlasmaQuick.so.5?
[debug 23:59:26.513513] - updating dock rect: "(682, 768) 0x0"
[debug 23:59:26.606606] - shell position: QPoint(0,768)
[debug 23:59:26.606606] - shell size: QSize(1366, 0)
[debug 23:59:26.606606] - updating dock rect: "(682, 768) 0x0"`

**Comment by audoban** [comment]
Instala por favor libqt5-qtquickcontrols2 o un paquete similar en tu distribucion, que provea QtQuick.Controls 2.0

**Comment by elav** [comment]
No hay ningún paquete que me provea eso en ArchLinux y los que están en AUR me dan error al tratar de compilar.. sigo buscando para ver si encuentro solución.. ;)

**Comment by audoban** [comment]
Ok entonces dejame yo eliminó la dependencia.

**Comment by audoban** [comment]
Hola Ernesto, perdon por la demora pero estaba terminando semestre.
Prueba ahora la version [master]. Tienes que agregar el icontask de Plasma5 manualmente desde buscador de plasmoides. Ten en cuenta que aun falta muchas opciones.
No te preocupes por la apariencia, en un futuro pretendo que sea customizable.

**Comment by elav** [comment]
Mmm, raro.. bajé la última versión, la compilé y demás y me sigue saliendo el mismo error:

````systeminside:build $ candil
[debug 16:13:32.05656] - package is valid true
[debug 16:13:32.05656] - Candil::DockCorona the package QJsonObject({"KPlugin":{"Authors":[{"Email":"audoban@openmailbox.org","Name":"audoban(smith ar)"}],"Id":"audoban.shell.candildock","License":"GPLv3+","Name":"Candil Dock Shell","Name[en]":"Candil Dock shell","Name[es]":"Shell de Candil Dock","ServiceTypes":["Plasma/Shell"],"Version":"1.0","Website":"https://github.com/audoban/CandilDock"},"Keywords":"shell","X-KDE-ParentApp":"candil"}) is valid!
[warning 16:13:32.116116] - "file:///usr/share/plasma/shells/audoban.shell.candildock/contents/views/Dock.qml" 
 "Error loading QML file.\n21: module \"QtQuick.Controls\" version 2.0 is not installed\n"
?libKF5Declarative.so.5?
[debug 16:13:32.116116] - containment changed
[debug 16:13:32.116116] - visibility mode Normal
[debug 16:13:32.116116] - candil wid: 81788941
[debug 16:13:32.116116] - showing temporarily
[warning 16:13:32.116116] - Could not set containment property on rootObject
?libKF5PlasmaQuick.so.5?
[debug 16:13:32.120120] - updating dock rect: "(682, 768) 0x0"
[debug 16:13:32.212212] - shell position: QPoint(0,768)
[debug 16:13:32.212212] - shell size: QSize(1366, 0)
[debug 16:13:32.212212] - updating dock rect: "(682, 768) 0x0"
````

**Comment by audoban** [comment]
Que pena Ernesto es que para la estupides no hay nada xD. Hice el commit pero no lo subi al repositorio.
Prueba de nuevo por favor, ya esta el cambio listo https://github.com/audoban/Candil-Dock/commit/2384ad9382e1e11b7022d0a970d9c4164c44b442.

**Comment by elav** [comment]
Ya logré que funcionara y voy a hacer un video, una especie de Review. Ahora, me asalta una duda.. donde guarda Candil su configuración? O sea, si quiero reiniciar sus valores por defecto.. que tengo que borrar o modificar?

**Comment by audoban** [comment]
Cierra primero el dock.
```bash
rm $HOME/.config/CandilDock-appletsrc
```
Y si vas hacer una review, ten encuenta por favor que aun falta la mitad de desarrollo.

Gracias por su paciencia :+1:

**Comment by elav** [comment]
Tranquilo que si tendré en cuenta que está en desarrollo, de hecho, para ser algo Beta está bastante bien.. ;)
